### ISSUE TITLE
Theatre Mode

### ISSUE THREAD

**Issue by arn7av** [arn7av/esl-facebook-stream#2]
We are lacking theatre mode at the moment. I am thinking to add a control on the control bar. A guide on how I think we can approach is looking at the fullscreen code:

button definition at https://github.com/arn7av/esl-facebook-stream/blob/master/src/esl_facebook_client/index.html#L221

activity catching at https://github.com/arn7av/esl-facebook-stream/blob/master/src/esl_facebook_client/app/contrib/akamai/controlbar/ControlBar.js#L84
https://github.com/arn7av/esl-facebook-stream/blob/master/src/esl_facebook_client/app/contrib/akamai/controlbar/ControlBar.js#L826

activity definition at https://github.com/arn7av/esl-facebook-stream/blob/master/src/esl_facebook_client/app/contrib/akamai/controlbar/ControlBar.js#L394

**Comment by jpjagt** [comment]
Hey, I've implemented theatre mode to the front-end, check my pull-request #5.
This one is very responsive (using fixed, max- and min-widths to ensure an optimal chat width for almost any resolution, however I don't think it works well on mobile devices), and the video is centered vertically (using flex).

Hopefully you approve of it, I think it works really well and would be a really nice feature for your project (which is awesome itself!)

**Comment by arn7av** [comment]
@JeroenPJ the code behaves perfectly and has been merged. The `isTheatre` state maintenance could have been done using javascript variables, but that doesn't provide us any advantage as of now (can maybe help in future when settings are needed to be remembered using cookies). Thanks a lot for the contribution!
